spring.application.name=pdf-chatbot-backend
server.port=8080

# ================================
# GROQ - comme ton amie
# ================================
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.chat.options.stream=false
spring.ai.openai.chat.options.stream-usage=false
spring.ai.openai.chat.options.max-tokens=2048
spring.ai.openai.embedding.enabled=false

# ================================
# CORS
# ================================
app.cors.allowed-origins=http://localhost:4200

# ================================
# UPLOAD
# ================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ================================
# LOGGING
# ================================
logging.level.com.pdfchatbot=DEBUG

spring.ai.retry.max-attempts=1